/*
MySQL Data Transfer
Source Host: localhost
Source Database: yiwei_server
Target Host: localhost
Target Database: yiwei_server
Date: 2013-4-23 22:26:17
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for skills_item
-- ----------------------------
CREATE TABLE `skills_item` (
  `skill_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL DEFAULT '',
  `itemids` varchar(255) DEFAULT NULL,
  `counts` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`skill_id`)
) ENGINE=MyISAM AUTO_INCREMENT=101422 DEFAULT CHARSET=utf8 COMMENT='MyISAM free: 10240 kB; MyISAM free: 10240 kB';

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `skills_item` VALUES ('1', '初级治愈术', '40503,40494,40520,40519', '10,50,100,10');
INSERT INTO `skills_item` VALUES ('2', '日光术', '40503,40494,40520,40519', '10,50,100,10');
INSERT INTO `skills_item` VALUES ('3', '保护罩', '40503,40494,40520,40519', '10,50,100,10');
INSERT INTO `skills_item` VALUES ('4', '光箭', '40503,40494,40520,40519', '10,50,100,10');
INSERT INTO `skills_item` VALUES ('5', '指定传送', '40503,40494,40520,40519', '10,50,100,10');
INSERT INTO `skills_item` VALUES ('6', '冰箭', '40503,40494,40520,40519', '10,50,100,10');
INSERT INTO `skills_item` VALUES ('7', '风刃', '40503,40494,40520,40519', '10,50,100,10');
INSERT INTO `skills_item` VALUES ('8', '神圣武器', '40503,40494,40520,40519', '10,50,100,10');
INSERT INTO `skills_item` VALUES ('9', '解毒术', '40495,40499,40505,88', '10,8,3,1');
INSERT INTO `skills_item` VALUES ('10', '寒冷战栗', '40495,40499,40505,88', '10,8,3,1');
INSERT INTO `skills_item` VALUES ('11', '毒咒', '40495,40499,40505,88', '10,8,3,1');
INSERT INTO `skills_item` VALUES ('12', '拟似魔法武器', '40495,40499,40505,88', '10,8,3,1');
INSERT INTO `skills_item` VALUES ('13', '无所遁形术', '40495,40499,40505,88', '10,8,3,1');
INSERT INTO `skills_item` VALUES ('14', '负重强化', '40495,40499,40505,88', '10,8,3,1');
INSERT INTO `skills_item` VALUES ('15', '火箭', '40495,40499,40505,88', '10,8,3,1');
INSERT INTO `skills_item` VALUES ('16', '地狱之牙', '40495,40499,40505,88', '10,8,3,1');
INSERT INTO `skills_item` VALUES ('17', '极光雷电', '40508,40504,40521,88', '45,3,3,3');
INSERT INTO `skills_item` VALUES ('18', '起死回生术', '40508,40504,40521,88', '45,3,3,3');
INSERT INTO `skills_item` VALUES ('19', '中级治愈术', '40508,40504,40521,88', '45,3,3,3');
INSERT INTO `skills_item` VALUES ('20', '闇盲咒术', '40508,40504,40521,88', '45,3,3,3');
INSERT INTO `skills_item` VALUES ('21', '铠甲护持', '40508,40504,40521,88', '45,3,3,3');
INSERT INTO `skills_item` VALUES ('22', '寒冰气息', '40508,40504,40521,88', '45,3,3,3');
INSERT INTO `skills_item` VALUES ('23', '能量感测', '40508,40504,40521,88', '45,3,3,3');
INSERT INTO `skills_item` VALUES ('24', 'none', null, null);
INSERT INTO `skills_item` VALUES ('25', '燃烧的火球', null, null);
INSERT INTO `skills_item` VALUES ('26', '通畅气脉术', null, null);
INSERT INTO `skills_item` VALUES ('27', '坏物术', null, null);
INSERT INTO `skills_item` VALUES ('28', '吸血鬼之吻', null, null);
INSERT INTO `skills_item` VALUES ('29', '缓速术', null, null);
INSERT INTO `skills_item` VALUES ('30', '岩牢', null, null);
INSERT INTO `skills_item` VALUES ('31', '魔法屏障', null, null);
INSERT INTO `skills_item` VALUES ('32', '冥想术', null, null);
INSERT INTO `skills_item` VALUES ('33', '木乃伊的诅咒', null, null);
INSERT INTO `skills_item` VALUES ('34', '极道落雷', null, null);
INSERT INTO `skills_item` VALUES ('35', '高级治愈术', null, null);
INSERT INTO `skills_item` VALUES ('36', '迷魅术', null, null);
INSERT INTO `skills_item` VALUES ('37', '圣洁之光', null, null);
INSERT INTO `skills_item` VALUES ('38', '冰锥', null, null);
INSERT INTO `skills_item` VALUES ('39', '魔力夺取', null, null);
INSERT INTO `skills_item` VALUES ('40', '黑闇之影', null, null);
INSERT INTO `skills_item` VALUES ('41', '造尸术', null, null);
INSERT INTO `skills_item` VALUES ('42', '体魄强健术', null, null);
INSERT INTO `skills_item` VALUES ('43', '加速术', null, null);
INSERT INTO `skills_item` VALUES ('44', '魔法相消术', null, null);
INSERT INTO `skills_item` VALUES ('45', '地裂术', null, null);
INSERT INTO `skills_item` VALUES ('46', '烈炎术', null, null);
INSERT INTO `skills_item` VALUES ('47', '弱化术', null, null);
INSERT INTO `skills_item` VALUES ('48', '祝福魔法武器', null, null);
INSERT INTO `skills_item` VALUES ('49', '体力回复术', null, null);
INSERT INTO `skills_item` VALUES ('50', '冰矛围篱', null, null);
INSERT INTO `skills_item` VALUES ('51', '召唤术', null, null);
INSERT INTO `skills_item` VALUES ('52', '神圣疾走', null, null);
INSERT INTO `skills_item` VALUES ('53', '龙卷风', null, null);
INSERT INTO `skills_item` VALUES ('54', '强力加速术', null, null);
INSERT INTO `skills_item` VALUES ('55', '狂暴术', null, null);
INSERT INTO `skills_item` VALUES ('56', '疾病术', null, null);
INSERT INTO `skills_item` VALUES ('57', '全部治愈术', null, null);
INSERT INTO `skills_item` VALUES ('58', '火牢', null, null);
INSERT INTO `skills_item` VALUES ('59', '冰雪暴', null, null);
INSERT INTO `skills_item` VALUES ('60', '隐身术', null, null);
INSERT INTO `skills_item` VALUES ('61', '返生术', null, null);
INSERT INTO `skills_item` VALUES ('62', '震裂术', null, null);
INSERT INTO `skills_item` VALUES ('63', '治愈能量风暴', null, null);
INSERT INTO `skills_item` VALUES ('64', '魔法封印', null, null);
INSERT INTO `skills_item` VALUES ('65', '雷霆风暴', null, null);
INSERT INTO `skills_item` VALUES ('66', '沉睡之雾', null, null);
INSERT INTO `skills_item` VALUES ('67', '变形术', null, null);
INSERT INTO `skills_item` VALUES ('68', '圣结界', null, null);
INSERT INTO `skills_item` VALUES ('69', '集体传送术', null, null);
INSERT INTO `skills_item` VALUES ('70', '火风暴', null, null);
INSERT INTO `skills_item` VALUES ('71', '药水霜化术', null, null);
INSERT INTO `skills_item` VALUES ('72', '强力无所遁形术', null, null);
INSERT INTO `skills_item` VALUES ('73', '创造魔法武器', null, null);
INSERT INTO `skills_item` VALUES ('74', '流星雨', null, null);
INSERT INTO `skills_item` VALUES ('75', '终极返生术', null, null);
INSERT INTO `skills_item` VALUES ('76', '集体缓速术', null, null);
INSERT INTO `skills_item` VALUES ('77', '究极光裂术', null, null);
INSERT INTO `skills_item` VALUES ('78', '绝对屏障', null, null);
INSERT INTO `skills_item` VALUES ('79', '灵魂升华', null, null);
INSERT INTO `skills_item` VALUES ('80', '冰雪飓风', null, null);
INSERT INTO `skills_item` VALUES ('81', 'none', null, null);
INSERT INTO `skills_item` VALUES ('82', 'none', null, null);
INSERT INTO `skills_item` VALUES ('83', 'none', null, null);
INSERT INTO `skills_item` VALUES ('84', 'none', null, null);
INSERT INTO `skills_item` VALUES ('85', 'none', null, null);
INSERT INTO `skills_item` VALUES ('86', 'none', null, null);
INSERT INTO `skills_item` VALUES ('87', '冲击之晕', null, null);
INSERT INTO `skills_item` VALUES ('88', '增幅防御', null, null);
INSERT INTO `skills_item` VALUES ('89', '尖刺盔甲', null, null);
INSERT INTO `skills_item` VALUES ('90', '坚固防护', null, null);
INSERT INTO `skills_item` VALUES ('91', '反击屏障', null, null);
INSERT INTO `skills_item` VALUES ('92', 'none', null, null);
INSERT INTO `skills_item` VALUES ('93', 'none', null, null);
INSERT INTO `skills_item` VALUES ('94', 'none', null, null);
INSERT INTO `skills_item` VALUES ('95', 'none', null, null);
INSERT INTO `skills_item` VALUES ('96', 'none', null, null);
INSERT INTO `skills_item` VALUES ('97', '暗隐术', null, null);
INSERT INTO `skills_item` VALUES ('98', '附加剧毒', null, null);
INSERT INTO `skills_item` VALUES ('99', '影之防护', null, null);
INSERT INTO `skills_item` VALUES ('100', '提炼魔石', null, null);
INSERT INTO `skills_item` VALUES ('101', '行走加速', null, null);
INSERT INTO `skills_item` VALUES ('102', '燃烧斗志', null, null);
INSERT INTO `skills_item` VALUES ('103', '暗黑盲咒', null, null);
INSERT INTO `skills_item` VALUES ('104', '毒性抵抗', null, null);
INSERT INTO `skills_item` VALUES ('105', '双重破坏', null, null);
INSERT INTO `skills_item` VALUES ('106', '暗影闪避', null, null);
INSERT INTO `skills_item` VALUES ('107', '暗影之牙', null, null);
INSERT INTO `skills_item` VALUES ('108', '会心一击', null, null);
INSERT INTO `skills_item` VALUES ('109', '力量提升', null, null);
INSERT INTO `skills_item` VALUES ('110', '敏捷提升', null, null);
INSERT INTO `skills_item` VALUES ('111', '闪避提升', null, null);
INSERT INTO `skills_item` VALUES ('112', 'none', null, null);
INSERT INTO `skills_item` VALUES ('113', '精准目标', null, null);
INSERT INTO `skills_item` VALUES ('114', '激励士气', null, null);
INSERT INTO `skills_item` VALUES ('115', '钢铁士气', null, null);
INSERT INTO `skills_item` VALUES ('116', '呼唤盟友', null, null);
INSERT INTO `skills_item` VALUES ('117', '冲击士气', null, null);
INSERT INTO `skills_item` VALUES ('118', '援护盟友', null, null);
INSERT INTO `skills_item` VALUES ('119', 'none', null, null);
INSERT INTO `skills_item` VALUES ('120', 'none', null, null);
INSERT INTO `skills_item` VALUES ('121', 'none', null, null);
INSERT INTO `skills_item` VALUES ('123', 'none', null, null);
INSERT INTO `skills_item` VALUES ('124', 'none', null, null);
INSERT INTO `skills_item` VALUES ('125', 'none', null, null);
INSERT INTO `skills_item` VALUES ('126', 'none', null, null);
INSERT INTO `skills_item` VALUES ('127', 'none', null, null);
INSERT INTO `skills_item` VALUES ('128', 'none', null, null);
INSERT INTO `skills_item` VALUES ('129', '魔法防御', null, null);
INSERT INTO `skills_item` VALUES ('130', '心灵转换', null, null);
INSERT INTO `skills_item` VALUES ('131', '世界树的呼唤', null, null);
INSERT INTO `skills_item` VALUES ('132', '三重矢', null, null);
INSERT INTO `skills_item` VALUES ('133', '弱化属性', null, null);
INSERT INTO `skills_item` VALUES ('134', '镜反射', null, null);
INSERT INTO `skills_item` VALUES ('135', 'none', null, null);
INSERT INTO `skills_item` VALUES ('136', 'none', null, null);
INSERT INTO `skills_item` VALUES ('137', '净化精神', null, null);
INSERT INTO `skills_item` VALUES ('138', '属性防御', null, null);
INSERT INTO `skills_item` VALUES ('139', 'none', null, null);
INSERT INTO `skills_item` VALUES ('140', 'none', null, null);
INSERT INTO `skills_item` VALUES ('141', 'none', null, null);
INSERT INTO `skills_item` VALUES ('142', 'none', null, null);
INSERT INTO `skills_item` VALUES ('143', 'none', null, null);
INSERT INTO `skills_item` VALUES ('144', 'none', null, null);
INSERT INTO `skills_item` VALUES ('145', '释放元素', null, null);
INSERT INTO `skills_item` VALUES ('146', '魂体转换', null, null);
INSERT INTO `skills_item` VALUES ('147', '单属性防御', null, null);
INSERT INTO `skills_item` VALUES ('148', '火焰武器', null, null);
INSERT INTO `skills_item` VALUES ('149', '风之神射', null, null);
INSERT INTO `skills_item` VALUES ('150', '风之疾走', null, null);
INSERT INTO `skills_item` VALUES ('151', '大地防护', null, null);
INSERT INTO `skills_item` VALUES ('152', '地面障碍', null, null);
INSERT INTO `skills_item` VALUES ('153', '魔法消除', null, null);
INSERT INTO `skills_item` VALUES ('154', '召唤属性精灵', null, null);
INSERT INTO `skills_item` VALUES ('155', '烈炎气息', null, null);
INSERT INTO `skills_item` VALUES ('156', '暴风之眼', null, null);
INSERT INTO `skills_item` VALUES ('157', '大地屏障', null, null);
INSERT INTO `skills_item` VALUES ('158', '生命之泉', null, null);
INSERT INTO `skills_item` VALUES ('159', '大地的祝福', null, null);
INSERT INTO `skills_item` VALUES ('160', '水之防护', null, null);
INSERT INTO `skills_item` VALUES ('161', '封印禁地', null, null);
INSERT INTO `skills_item` VALUES ('162', '召唤强力属性精灵', null, null);
INSERT INTO `skills_item` VALUES ('163', '烈炎武器', null, null);
INSERT INTO `skills_item` VALUES ('164', '生命的祝福', null, null);
INSERT INTO `skills_item` VALUES ('165', '生命呼唤', null, null);
INSERT INTO `skills_item` VALUES ('166', '暴风神射', null, null);
INSERT INTO `skills_item` VALUES ('167', '风之枷锁', null, null);
INSERT INTO `skills_item` VALUES ('168', '钢铁防护', null, null);
INSERT INTO `skills_item` VALUES ('169', '体能激发', null, null);
INSERT INTO `skills_item` VALUES ('170', '水之元气', null, null);
INSERT INTO `skills_item` VALUES ('171', '属性之火', null, null);
INSERT INTO `skills_item` VALUES ('172', '暴风疾走', null, null);
INSERT INTO `skills_item` VALUES ('173', '污浊之水', null, null);
INSERT INTO `skills_item` VALUES ('174', '精准射击', null, null);
INSERT INTO `skills_item` VALUES ('175', '烈焰之魂', null, null);
INSERT INTO `skills_item` VALUES ('176', '能量激发', null, null);
INSERT INTO `skills_item` VALUES ('177', 'none', null, null);
INSERT INTO `skills_item` VALUES ('178', 'none', null, null);
INSERT INTO `skills_item` VALUES ('179', 'none', null, null);
INSERT INTO `skills_item` VALUES ('180', 'none', null, null);
INSERT INTO `skills_item` VALUES ('181', '龙之护铠', null, null);
INSERT INTO `skills_item` VALUES ('182', '燃烧击砍', null, null);
INSERT INTO `skills_item` VALUES ('183', '护卫毁灭', null, null);
INSERT INTO `skills_item` VALUES ('184', '岩浆喷吐', null, null);
INSERT INTO `skills_item` VALUES ('185', '觉醒：安塔瑞斯', null, null);
INSERT INTO `skills_item` VALUES ('186', '血之渴望', null, null);
INSERT INTO `skills_item` VALUES ('187', '屠宰者', null, null);
INSERT INTO `skills_item` VALUES ('188', '恐惧无助', null, null);
INSERT INTO `skills_item` VALUES ('189', '冲击之肤', null, null);
INSERT INTO `skills_item` VALUES ('190', '觉醒：法利昂', null, null);
INSERT INTO `skills_item` VALUES ('191', '致命身躯', null, null);
INSERT INTO `skills_item` VALUES ('192', '夺命之雷', null, null);
INSERT INTO `skills_item` VALUES ('193', '惊悚死神', null, null);
INSERT INTO `skills_item` VALUES ('194', '寒冰喷吐', null, null);
INSERT INTO `skills_item` VALUES ('195', '觉醒：巴拉卡斯', null, null);
INSERT INTO `skills_item` VALUES ('196', 'none', null, null);
INSERT INTO `skills_item` VALUES ('197', 'none', null, null);
INSERT INTO `skills_item` VALUES ('198', 'none', null, null);
INSERT INTO `skills_item` VALUES ('199', 'none', null, null);
INSERT INTO `skills_item` VALUES ('200', 'none', null, null);
INSERT INTO `skills_item` VALUES ('201', '镜像', null, null);
INSERT INTO `skills_item` VALUES ('202', '混乱', null, null);
INSERT INTO `skills_item` VALUES ('203', '暴击', null, null);
INSERT INTO `skills_item` VALUES ('204', '幻觉：欧吉', null, null);
INSERT INTO `skills_item` VALUES ('205', '立方：燃烧', null, null);
INSERT INTO `skills_item` VALUES ('206', '专注', null, null);
INSERT INTO `skills_item` VALUES ('207', '心灵破坏', null, null);
INSERT INTO `skills_item` VALUES ('208', '骷髅毁坏', null, null);
INSERT INTO `skills_item` VALUES ('209', '幻觉：巫妖', null, null);
INSERT INTO `skills_item` VALUES ('210', '立方：地裂', null, null);
INSERT INTO `skills_item` VALUES ('211', '耐力', null, null);
INSERT INTO `skills_item` VALUES ('212', '幻想', null, null);
INSERT INTO `skills_item` VALUES ('213', '武器破坏者', null, null);
INSERT INTO `skills_item` VALUES ('214', '幻觉：钻石高仑', null, null);
INSERT INTO `skills_item` VALUES ('215', '立方：冲击', null, null);
INSERT INTO `skills_item` VALUES ('216', '洞察', null, null);
INSERT INTO `skills_item` VALUES ('217', '恐慌', null, null);
INSERT INTO `skills_item` VALUES ('218', '疼痛的欢愉', null, null);
INSERT INTO `skills_item` VALUES ('219', '幻觉：化身', null, null);
INSERT INTO `skills_item` VALUES ('220', '立方：和谐', null, null);
